version: '3'

volumes:
  product-db-data:
    driver: local

services:
  product_db:
    container_name: product_db
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - product-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=product
    restart: always
    ports:
      - "13306:3306"
  product:
    container_name: product-service
    build:
      context: .
    ports:
      - 5558:5558
    links:
      - product_db
    depends_on:
      - product_db
    restart: on-failure


# mysql --host=0.0.0.0 --port=13306 -u root